# Configurations
title:            码农老王开户
longtitle:        专注于万1免5开户，聚合多家优质券商，免费寻求最低的交易费率
keywords:         万一免五,万一免五券商开户,万1免5,万1免5开户，万一免五永久有效
author:           韭菜老王
email:            qing606@gmail.com
description: >
  专注于万1免5开户，聚合多家优质券商，免费寻求最低的交易费率。股票交易最低万0.75免5，北交所最低万1.75免5全佣，两融费率低至2.99%,港股通万0.3静佣金，ETF万0.5免5，支持同花顺，支持通达信，超强条件单，量化交易优选

version:          1.0
gitbook_version:  3.2.3

url:              'https://mian5.netqq.net'
baseurl:          ''
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min:   2
  h_max:   3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - posts
  - pages
  - others

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji


tracker:
  google_analytics: "G-HNLW1TZV86"